CREATE TABLE cf_genre
(
    id   NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR2(255),
    CONSTRAINT pk_cf_genre PRIMARY KEY (id)
);

CREATE TABLE cf_movie
(
    id             NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR2(255),
    description    VARCHAR2(255),
    release_date   date,
    average_rating DECIMAL,
    CONSTRAINT pk_cf_movie PRIMARY KEY (id)
);

CREATE TABLE cf_movie_genres
(
    genre_id NUMBER(38, 0) NOT NULL,
    movie_id NUMBER(38, 0) NOT NULL,
    CONSTRAINT pk_cf_movie_genres PRIMARY KEY (genre_id, movie_id)
);

CREATE TABLE cf_movie_list
(
    id      NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR2(255),
    user_id NUMBER(38, 0),
    CONSTRAINT pk_cf_movie_list PRIMARY KEY (id)
);

CREATE TABLE cf_movie_list_movies
(
    movie_id      NUMBER(38, 0) NOT NULL,
    movie_list_id NUMBER(38, 0) NOT NULL
);

CREATE TABLE cf_review
(
    id       NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  NUMBER(38, 0),
    movie_id NUMBER(38, 0),
    rating   DECIMAL,
    comments VARCHAR2(255),
    CONSTRAINT pk_cf_review PRIMARY KEY (id)
);

CREATE TABLE cf_user
(
    id       NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR2(255),
    email    VARCHAR2(255),
    password VARCHAR2(255),
    age      INTEGER,
    is_admin NUMBER(1),
    CONSTRAINT pk_cf_user PRIMARY KEY (id)
);

ALTER TABLE cf_movie_list
    ADD CONSTRAINT FK_CF_MOVIE_LIST_ON_USER FOREIGN KEY (user_id) REFERENCES cf_user (id);

ALTER TABLE cf_review
    ADD CONSTRAINT FK_CF_REVIEW_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_review
    ADD CONSTRAINT FK_CF_REVIEW_ON_USER FOREIGN KEY (user_id) REFERENCES cf_user (id);

ALTER TABLE cf_movie_genres
    ADD CONSTRAINT fk_cfmovgen_on_genre FOREIGN KEY (genre_id) REFERENCES cf_genre (id);

ALTER TABLE cf_movie_genres
    ADD CONSTRAINT fk_cfmovgen_on_movie FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_movie_list_movies
    ADD CONSTRAINT fk_cfmovlismov_on_movie FOREIGN KEY (movie_id) REFERENCES cf_movie (id);

ALTER TABLE cf_movie_list_movies
    ADD CONSTRAINT fk_cfmovlismov_on_movie_list FOREIGN KEY (movie_list_id) REFERENCES cf_movie_list (id);