CREATE TABLE cf_genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE cf_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    age      INTEGER,
    is_admin BOOLEAN
);

CREATE TABLE cf_movie
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    description    TEXT,
    release_date   DATE,
    average_rating DOUBLE PRECISION
);

CREATE TABLE cf_review
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT,
    movie_id BIGINT,
    rating   DOUBLE PRECISION,
    comment  TEXT,

    CONSTRAINT fk_cf_review_user
        FOREIGN KEY (user_id)
            REFERENCES cf_user (id),

    CONSTRAINT fk_cf_review_movie
        FOREIGN KEY (movie_id)
            REFERENCES cf_movie (id)
);

CREATE TABLE cf_movie_list
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    user_id BIGINT,

    CONSTRAINT fk_cf_movielist_user
        FOREIGN KEY (user_id)
            REFERENCES cf_user (id)
);

-- RELACIONAMENTO MOVIE ↔ GENRE

CREATE TABLE cf_movie_genres
(
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,

    PRIMARY KEY (movie_id, genre_id),

    CONSTRAINT fk_cf_movie_genre_movie
        FOREIGN KEY (movie_id)
            REFERENCES cf_movie (id),

    CONSTRAINT fk_cf_movie_genre_genre
        FOREIGN KEY (genre_id)
            REFERENCES cf_genre (id)
);

-- RELACIONAMENTO MOVIELIST ↔ MOVIE

CREATE TABLE cf_movie_list_movies
(
    movie_list_id BIGINT NOT NULL,
    movie_id      BIGINT NOT NULL,

    PRIMARY KEY (movie_list_id, movie_id),

    CONSTRAINT fk_cf_movielist_movie
        FOREIGN KEY (movie_list_id)
            REFERENCES cf_movie_list (id),

    CONSTRAINT fk_cf_movielist_movie_ref
        FOREIGN KEY (movie_id)
            REFERENCES cf_movie (id)
);